# Generated by Django 3.2.8 on 2022-06-03 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=50, verbose_name='User_Name')),
                ('user_email', models.EmailField(blank=True, db_column='user_email', max_length=100, null=True, verbose_name='User_Email')),
                ('request_token', models.CharField(blank=True, db_column='request_token', max_length=50, null=True, verbose_name='Request_Token')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Request_Token',
            },
        ),
    ]
