# Generated by Django 3.2.8 on 2022-06-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='city',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='user_pwd',
        ),
    ]
