# Generated by Django 3.2.8 on 2022-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20220601_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='addres',
        ),
        migrations.AddField(
            model_name='upload_file',
            name='decription',
            field=models.TextField(blank=True, db_column='decription', max_length=50, null=True, verbose_name='Decription'),
        ),
    ]
