# Generated by Django 3.2.8 on 2022-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20220601_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='user_name',
        ),
        migrations.AddField(
            model_name='upload_file',
            name='Key',
            field=models.CharField(blank=True, db_column='key', max_length=500, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='file_data',
            field=models.TextField(blank=True, db_column='file_data', max_length=100, null=True, verbose_name='File_Data'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='file_name',
            field=models.CharField(blank=True, db_column='file_name', max_length=50, null=True, verbose_name='File_Name'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='file_size',
            field=models.BigIntegerField(blank=True, db_column='file_size', null=True, verbose_name='File_Size'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='file_type',
            field=models.CharField(blank=True, db_column='file_type', max_length=50, null=True, verbose_name='File_Type'),
        ),
    ]
