# Generated by Django 3.2.8 on 2022-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20220602_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='user_name',
            field=models.CharField(blank=True, db_column='user_name', max_length=50, null=True, verbose_name='User_Name'),
        ),
    ]
