# Generated by Django 3.2.8 on 2022-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_upload_file_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='file_size',
            field=models.FloatField(blank=True, db_column='file_size', null=True, verbose_name='File_Size'),
        ),
    ]
