# Generated by Django 3.2.8 on 2022-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_upload_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='file_size',
            field=models.TextField(blank=True, db_column='file_size', null=True, verbose_name='File_Size'),
        ),
    ]
