# Generated by Django 3.2.8 on 2022-06-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_upload_file_request_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='Key',
            field=models.TextField(blank=True, db_column='key', max_length=500, null=True, verbose_name='Key'),
        ),
    ]
