# Generated by Django 3.2.8 on 2022-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20220606_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='screat_key',
            field=models.TextField(blank=True, db_column='screat_key', max_length=100, null=True, verbose_name='Screat_Key'),
        ),
    ]
