# Generated by Django 3.2.8 on 2022-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_request_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='request_mail',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='screat_key',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='status',
        ),
        migrations.AddField(
            model_name='request_file',
            name='request_mail',
            field=models.EmailField(blank=True, db_column='request_mail', max_length=100, null=True, verbose_name='Request_Mail'),
        ),
    ]
