# Generated by Django 3.2.8 on 2022-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20220608_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_file',
            name='user_id',
            field=models.CharField(blank=True, db_column='user_id', max_length=50, null=True, verbose_name='User_id'),
        ),
    ]
