# Generated by Django 3.2.8 on 2022-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_request_file_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_file',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
