# Generated by Django 3.2.8 on 2022-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_request_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_file',
            name='user_file',
            field=models.FileField(blank=True, db_column='user_file', upload_to='User/Files/', verbose_name='User_File'),
        ),
    ]
